name: Build and Test 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIRALAND_VERSION: 1.14.17

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      cache_id: amman 
    steps:
      - uses: actions/checkout@v2

      # Setup Miraland Test Validator required by Amman
      - uses: ./.github/actions/install-miraland
        with: 
          miraland_version: ${{ env.MIRALAND_VERSION }}

      # Build and Test
      - name: install-deps-and-build
        run: |
          yarn install  
          yarn build

      # Run tests
      - name: test-amman 
        working-directory: ./amman-tests
        run: DEBUG=amman* yarn test 
